---
title: "Milestone #2"
author: "Group 22: Jaemie Anne Abad, Vig Karthik, Kathy LeBert"
date: "2023-10-01"
output: html
---


#Description of dataset
*What is the data source? (1-2 sentences on where the data is coming from, dates included, etc.)*
The major data are from California Office of Environmental Health Hazard Assessment's CalEnviroScreen 4.0. 
The asthma emergency department visit rates is from California Health and Human Services Open Data Portal.


*How does the dataset relate to the group problem statement and question?*
The groups problem statement and question looks at the correlation between each county's ED visits due to asthma and certain Cal Environ Screen scores. To answer this question, the datasets needed are the rate ED visits and each CES measures - which are the ones provided. 


```{r clean up columns - Vig}
library(data.table)

#loading the data.table library to read in the csv
#also loaded read_xl to read the xlsx file

data_dictionary <- read_xlsx("calenviroscreen_datadictionary.xlsx")
#using read_xlsx to read in the data dictionary

measures_raw <- fread("calenviroscreen_measures_2021.csv", encoding = "UTF-8")
#using fread() from the data.table package to read the measures csv.
#using fread() so special characters read in properly

scores_raw <- fread("calenviroscreen_scores_demog_2021.csv", encoding = "UTF-8")
#using fread() to read the demographics csv

asthma_raw <- fread("chhs_asthma_ed.csv")
#using fread() to read the asthma csv.

#now that we've read the files, I've went into the csv files and removed 
#periods by some abbreviations to avoid '._' string chunks in columns
#this is mostly for aesthetic and typing ease during the project

#the below functions take the raw csvs and convert all columns to lowercase
#they also remove spaces in the column names to convert columns to snakecase

measures <- rename_with(
  measures_raw,             # data frame
  ~ tolower(           # function call (using tolower())
    gsub(" ",          # embedded gsub() checking for empty spaces pattern " "
         "_",          # replace pattern with underscore "_"         
         .x,           
         fixed = TRUE) 
    ))

scores <- rename_with(
  scores_raw,             # data frame
  ~ tolower(           # function call (using tolower())
    gsub(" ",          # embedded gsub() checking for empty spaces pattern " "
         "_",          # replace pattern with underscore "_"         
         .x,           
         fixed = TRUE) 
    ))


asthma <- rename_with(
  asthma_raw,             # data frame
  ~ tolower(           # function call (using tolower())
    gsub(" ",          # embedded gsub() checking for empty spaces pattern " "
         "_",         # replace pattern with underscore "_"          
         .x,           
         fixed = TRUE) 
    ))

str(measures)
str(scores)
str(asthma)

#I checked the dataframe structure to see if we needed to change column types.
#The column types seem to be accurately assigned. Based on the column
#descriptors, there seems to be no mismatch of data types. Characters are
#characters, integers are integers, and decimals are numbers.

```



#Describe cleaning that each data source may need
NOTE: There is no requirement for any data cleaning in this milestone. Please just list out the anticipated data cleaning needed. 
Examples:
*Data elements that need to be converted to a different type*
-May have to convert Census Tract numbers to characters
-Convert CES percentile range to characters


*Data elements that need cleaning or re-categorization*
-Convert demographic percentages to raw numbers
-Rounding decimal points to just 2 after for most of the CES scores and percentile


*Data elements that may be used for future joins (i.e. state, county)*
-County CES scores with county ED visit rates due to asthma
